variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GPU_1: 2
  GPU_2: 3

stages:
- build
- upload
- start


build:
  stage: build
  tags: 
  - RapidsDL
  script:
  - docker build -t jengpu -f jengpu.Dockerfile .

upload:
  stage: upload
  tags:
  - RapidsDL
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker tag jengpu gitlab-master.nvidia.com:5005/rapidsdl/jenkinsgpu/jengpu:latest
  - docker push gitlab-master.nvidia.com:5005/rapidsdl/jenkinsgpu/jengpu:latest

start:
  stage: start
  tags:
  - RapidsDL
  script:
  - if \[ "$(docker ps | grep jenkins-blueocean)" ]; then docker kill  $(docker ps -a -q --filter "name=jenkins-blueocean"); fi
    #- if \[ "$(docker ps -a --filter "name=jenkins-blueocean")" ];  then docker rm  $(docker ps -a -q --filter "name=jenkins-blueocean"); fi
  - docker run   --name jenkins-blueocean   --rm  --network jenkins   --env DOCKER_HOST=tcp://docker:2376   --env DOCKER_CERT_PATH=/certs/client   --env DOCKER_TLS_VERIFY=1   --publish 8080:8080   --publish 50000:50000   --volume jenkins-data:/var/jenkins_home   --volume jenkins-docker-certs:/certs/client:ro --runtime=nvidia --ipc=host --detach gitlab-master.nvidia.com:5005/rapidsdl/jenkinsgpu/jengpu:latest 
